# Generated by Django 2.0 on 2018-11-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='date_ended',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wh',
            name='date_ended',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wh',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
    ]
