# Generated by Django 2.0 on 2018-10-31 04:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'unattended'), (1, 'candidate'), (2, 'not qualified'), (3, 'over qualified'), (4, 'delisted'), (5, 'winner')], default=0, verbose_name='status')),
                ('date_applied', models.DateTimeField(auto_now_add=True, verbose_name='date applied')),
            ],
            options={
                'ordering': ['date_applied'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['cate_name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('telephone', models.IntegerField(blank=True, null=True)),
                ('fax', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, default='')),
                ('date_add', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='date created')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Open'), (2, 'Suspended'), (3, 'Filled'), (4, 'Cancelled')], default=1, verbose_name='status')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('location', models.CharField(blank=True, max_length=64)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date update')),
                ('category', models.ManyToManyField(to='jobs.Category')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='jobs.Company')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['date_updated'],
            },
        ),
    ]
