# Generated by Django 2.0 on 2018-10-31 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='added_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.CompanyProfile'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='job', to='jobs.Job'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='job_applicant', to='users.StudentProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='applicant',
            unique_together={('user', 'job')},
        ),
    ]
